### PR TITLE
refactor: 2d default material

### PR DESCRIPTION
**Pull request by singlecoder**
### Please check if the PR fulfills these requirements

- [ ] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by eyworldwide** [comment]
Please review code before merge .

**Comment by singlecoder** [comment]
> Please review code before merge .

???

**Comment by eyworldwide** [comment]
@singlecoder Ops, it's closed. I assumed it was merged.

**Comment by eyworldwide** [comment]
Write the reason why close it, if there is a new PR please commit the link it in the comment : )

**Pull request closed without merging**
