### PR TITLE
fix: get pixel buffer use mip level should right shift

### PR DESCRIPTION
**Pull request by gz65555**
### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Bug fix

### What is the current behavior? (You can also link to an open issue here)
Has bug in get pixel buffer

### What is the new behavior (if this is a feature change)?
Calculate correct width and height.

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
No

### CODE REVIEW

**Comment by zhuxudong** [comment]
i think it's not bug, if you wanna get/set mip data, you can coding like below:
image

**Comment by gz65555** [comment]
Seems like reloading `getPixelBuffer(miplevel, arrayBufferView)` is meaningless. If you use method like this way, you'll get error data for now.

**Comment by zhuxudong** [comment]
> 

you are right! `getPixelBuffer(miplevel, arrayBufferView)` has not been tested

**Review by zhuxudong — APPROVED** [review]
+1

**Review by GuoLei1990 — APPROVED** [review]
+1

**Pull request merged**
