### PR TITLE
perf: add createImageBitmap decode image

### PR DESCRIPTION
**Pull request by gz65555**
### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Add `createImageBitmap` api to async decode image.

### CODE REVIEW

**Comment by cl1069573062** [comment]
Was this solution eventually applied? It doesn't seem to have been merged into the master branch. Could you explain the reasoning behind this decision?

**Comment by gz65555** [comment]
> Was this solution eventually applied? It doesn't seem to have been merged into the master branch. Could you explain the reasoning behind this decision?

@cl1069573062 The implemetion of `createImageBitmap` still has a bug, and I have submitted an issue to the Chrome team, but there has been no progress so far. https://bugs.chromium.org/p/chromium/issues/detail?id=1164969

**Comment by cl1069573062** [comment]
Thank you for your response

I would like to inquire whether the phenomenon of imageBitmap not speeding up is present in only a small number of devices, or if it is common among most devices. We are also considering using this strategy, but we have not been able to verify it with you and are concerned about potential issues. If imageBitmap can significantly speed up most devices, we may consider using it

**Comment by gz65555** [comment]
I'm not sure, I mostly tested on chrome browser and a small number of android devices. But Google confirmed that this is a chromium issue, so it should be general. You can try it yourself.

**Pull request closed without merging**
