### PR TITLE
fix: fix ShaderData.setInt() invalid bug.

### PR DESCRIPTION
**Pull request by GuoLei1990**
### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Bug fix.

### What is the current behavior? (You can also link to an open issue here)
ShaderData.setInt() maybe invalid.

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
No.

### CODE REVIEW

**Review by gz65555 — APPROVED** [review]
+1

**Review by singlecoder — COMMENTED** [review]
+1

**Review by jserranoq — COMMENTED** [review]
N

**Review by jserranoq — COMMENTED** [review]
N

**Review by jserranoq — COMMENTED** [review]
M

**Pull request merged**
